# Change these first
owner: jg3hlx # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
   - name: XLX016
     url: xrf016.xreflector-jp.org
   - name: XLX052
     url: xrf052.xreflector-jp.org
   - name: XLX058
     url: xrf058.xreflector-jp.org
   - name: XLX064
     url: xrf064.owari.biz
   - name: XLX076
     url: xrf076.xreflector-jp.org
   - name: XLX081
     url: xrf081.mydns.jp
   - name: XLX085
     url: xrf085.mydns.jp
   - name: XLX095
     url: xrf095.xreflector-jp.org
   - name: XLX098
     url: xrf098.mydns.jp
   - name: XLX111
     url: xrf111.xreflector-jp.org
   - name: XLX124
     url: xrf124.xreflector-jp.org
   - name: XLX129
     url: guwgw.cir-ins.com
   - name: XLX176
     url: xrf176.xreflector-jp.org
   - name: XLX220
     url: xlx220.sapotech.com
   - name: XLX224
     url: xrf224.xreflector-jp.org
   - name: XLX225
     url: xrf225.xreflector-jp.org
   - name: XLX291
     url: xrf291.xreflector-jp.org
   - name: XLX326
     url: xrf326.xreflector-jp.org
   - name: XLX360
     url: xrf360.xreflector-jp.org
   - name: XLX373
     url: xrf373.mydns.jp
   - name: XLX380
     url: kdk.ddns.net
   - name: XLX412
     url: xrf412.xreflector-jp.org
   - name: XLX431
     url: xrf431.xreflector-jp.org
   - name: XLX435
     url: xrf435.xreflector-jp.org
   - name: XLX440
     url: xrf440.e-kyushu.net
   - name: XLX441
     url: xrf441.xreflector-jp.org
   - name: XLX459
     url: xrf459.xreflector-jp.org
   - name: XLX464
     url: ref.ah-huh.net
   - name: XLX499
     url: xrf499.xreflector-jp.org
   - name: XLX510
     url: xrf510.xreflector-jp.org
   - name: XLX514
     url: xrf514.xreflector-jp.org
   - name: XLX515
     url: xrf515.xreflector-jp.org
   - name: XLX538
     url: xrf538.mydns.jp
   - name: XLX560
     url: xrf560.xreflector-jp.org
   - name: XLX583
     url: xrf583.mydns.jp
   - name: XLX599
     url: xrf599.xreflector-jp.org
   - name: XLX608
     url: xrf608.xreflector-jp.org
   - name: XLX630
     url: xrf630.xreflector-jp.org
   - name: XLX673
     url: xrf673.xreflector-jp.org
   - name: XLX698
     url: xrf698.xreflector-jp.org
   - name: XLX701
     url: xrf701.xreflector-jp.org
   - name: XLX703
     url: xrf703.xreflector-jp.org
   - name: XLX704
     url: xrf704.xreflector-jp.org
   - name: XLX705
     url: xrf705.xreflector-jp.org
   - name: XLX708
     url: xrf708.xreflector-jp.org
   - name: XLX712
     url: xrf712.mydns.jp
   - name: XLX713
     url: xrf713.xreflector-jp.org
   - name: XLX741
     url: xrf741.xreflector-jp.org
   - name: XLX738
     url: xlx738.jq2sai.net
   - name: XLX753
     url: xrf753.xreflector-jp.org
   - name: XLX770
     url: xrf770.mydns.jp
   - name: XLX776
     url: 776.bayfm78.tokyo
   - name: XLX781
     url: xrf781.xreflector-jp.org
   - name: XLX791
     url: xrf791.xreflector-jp.org
   - name: XLX807
     url: xrf807.owari.biz
   - name: XLX812
     url: xrf812.xreflector-jp.org
   - name: XLX878
     url: xrf878.xreflector-jp.org
   - name: XLX883
     url: xrf883.mydns.jp
   - name: XLX904
     url: xrf904.xreflector-jp.org
   - name: XLX940
     url: xrf940.xreflector-jp.org
   - name: XLX944
     url: xrf944.xreflector-jp.org
   - name: XLX959
     url: xrf959.xreflector-jp.org
   - name: XLX970
     url: xlx970.onogoro.net
   - name: XLX992
     url: xrf992.xreflector-jp.org
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
 ## cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
