# Change these first
owner: jg3hlx # Your GitHub username
repo: upptime # Your GitHub repository name


# Add your sites here
sites:
   - name: XLX016
     url: http://xrf016.xreflector-jp.org
   - name: XLX052
     url: http://xrf052.xreflector-jp.org
   - name: XLX058
     url: http://xrf058.xreflector-jp.org
   - name: XLX064
     url: http://xrf064.owari.biz
   - name: XLX076
     url: http://xrf076.xreflector-jp.org
   - name: XLX081
     url: http://xrf081.mydns.jp
   - name: XLX085
     url: http://xrf085.mydns.jp
   - name: XLX095
     url: http://xrf095.xreflector-jp.org
   - name: XLX098
     url: http://xrf098.mydns.jp
   - name: XLX111
     url: http://xrf111.xreflector-jp.org
   - name: XLX124
     url: http://xrf124.xreflector-jp.org
#   - name: XLX129
#     url: http://jm1ydn.cir-ins.com
   - name: XLX176
     url: http://xrf176.xreflector-jp.org
   - name: XLX220
     url: http://xlx220.sapotech.com
   - name: XLX224
     url: http://xrf224.xreflector-jp.org
   - name: XLX225
     url: http://xrf225.xreflector-jp.org
   - name: XLX291
     url: http://xrf291.xreflector-jp.org
   - name: XLX326
     url: http://xrf326.xreflector-jp.org
   - name: XLX360
     url: http://xrf360.xreflector-jp.org
   - name: XLX373
     url: http://xrf373.mydns.jp
   - name: XLX380
     url: http://kdk.ddns.net
   - name: XLX412
     url: http://xrf412.xreflector-jp.org
   - name: XLX431
     url: http://xrf431.xreflector-jp.org
   - name: XLX435
     url: http://xrf435.xreflector-jp.org
   - name: XLX440
     url: http://xrf440.e-kyushu.net
   - name: XLX441
     url: http://xrf441.xreflector-jp.org
   - name: XLX459
     url: http://xrf459.xreflector-jp.org
   - name: XLX464
     url: http://ah-huh.net/xlx/
   - name: XLX499
     url: http://xrf499.xreflector-jp.org
   - name: XLX510
     url: http://xrf510.xreflector-jp.org
   - name: XLX514
     url: http://xrf514.xreflector-jp.org
   - name: XLX515
     url: http://xrf515.xreflector-jp.org
   - name: XLX538
     url: http://xrf538.mydns.jp
   - name: XLX560
     url: http://xrf560.xreflector-jp.org
   - name: XLX583
     url: http://xrf583.mydns.jp
   - name: XLX599
     url: http://xrf599.xreflector-jp.org
   - name: XLX608
     url: http://xrf608.xreflector-jp.org
   - name: XLX630
     url: http://xrf630.xreflector-jp.org
   - name: XLX673
     url: http://xrf673.xreflector-jp.org
   - name: XLX698
     url: http://xrf698.xreflector-jp.org
   - name: XLX701
     url: http://xrf701.xreflector-jp.org
   - name: XLX703
     url: http://xrf703.xreflector-jp.org
   - name: XLX704
     url: http://xrf704.xreflector-jp.org
   - name: XLX705
     url: http://xrf705.xreflector-jp.org
   - name: XLX708
     url: http://xrf708.xreflector-jp.org
   - name: XLX712
     url: http://xrf712.mydns.jp
   - name: XLX713
     url: http://xrf713.xreflector-jp.org
   - name: XLX741
     url: http://xrf741.xreflector-jp.org
   - name: XLX738
     url: http://xlx738.jq2sai.net
   - name: XLX753
     url: http://xrf753.xreflector-jp.org
#   - name: XLX770
#     url: http://xrf770.mydns.jp
   - name: XLX776
     url: http://776.bayfm78.tokyo
   - name: XLX781
     url: http://xrf781.xreflector-jp.org
   - name: XLX794
     url: http://xrf794.xreflector-jp.org
   - name: XLX807
     url: http://xrf807.owari.biz
   - name: XLX812
     url: http://xrf812.xreflector-jp.org
   - name: XLX878
     url: http://xrf878.xreflector-jp.org
   - name: XLX883
     url: http://xrf883.mydns.jp
   - name: XLX904
     url: http://xrf904.xreflector-jp.org
   - name: XLX940
     url: http://xrf940.xreflector-jp.org
   - name: XLX944
     url: http://xrf944.xreflector-jp.org
   - name: XLX959
     url: http://xrf959.xreflector-jp.org
   - name: XLX970
     url: http://xlx970.onogoro.net
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
 ## cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
